execute: vertex.cpp vertex.h triangle.cpp triangle.h halfedge.cpp halfedge.h mesh.cpp mesh.h driver.cpp
	g++ -g -Wall --std=c++11 driver.cpp mesh.cpp triangle.cpp halfedge.cpp vertex.cpp -o driver.exe
